### ISSUE TITLE
Blank browser screen

### ISSUE THREAD

**Issue by lebogan** [vladfaust/crystalworld#4]
This looks like an interesting project so I cloned it and built the production server. I made the postgresql database and exported all my environment variables. The server runs on 0.0.0.0:5000, however my browser is blank and the server screen doesn't show any http responses - not even refresh requests.

I can't find any html so I assume I have to build that? Views too?

My web app experience has been with Kemal so I'm kinda lost.

Any help is greatly appreciated. Thank you.

**Comment by vladfaust** [comment]
Hello, @lebogan,

Crystal World is a pure back-end **API** implementation, so the only rendering it's capable of is JSON rendering. It follows [RealWorld API specs](https://github.com/gothinkster/realworld/tree/master/api). 

As seen in

https://github.com/vladfaust/crystalworld/blob/c84a9c54b993949c569729ded5260404c34370c3/src/app/router.cr#L8

"/" path returns a blank 200 response. I should probably add something like "Hello Crystal World" here.

*P.S:* Prism supports generic templating interface called [Kilt](https://github.com/jeromegn/kilt).

**Comment by lebogan** [comment]
Thanks for the response. I'll checkout Kilt.
