### ISSUE TITLE
Instructions for deploying with a front-end

### ISSUE THREAD

**Issue by dscottboggs** [vladfaust/crystalworld#7]
It would be nice if there were a way to drop a given front-end into a folder, and have an action which either returns a plain 200 for the default or the contents of a folder if it's present.

**Comment by vladfaust** [comment]
Sorry, but that seems strange to me. Realworld applications are pure back-ends and front-ends. If a user wants to have a front-end for Crystalworld, then they should grab one from https://realworld.io and install it separately.
